
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aman Goyal
 */
public class Page_2 extends javax.swing.JFrame {
    public int welRows[] = new int[100];

    /**
     * Creates new form Page_2
     */
    public Page_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ped = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        nxt = new javax.swing.JButton();
        rmv = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        search = new javax.swing.JLayeredPane();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        bs3 = new javax.swing.JButton();
        bs1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        bs2 = new javax.swing.JButton();
        bs4 = new javax.swing.JButton();
        nwstk = new javax.swing.JLayeredPane();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tinsert = new javax.swing.JTable();
        df1 = new javax.swing.JTextField();
        df2 = new javax.swing.JTextField();
        df3 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();

        ped.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ped.setMinimumSize(new java.awt.Dimension(680, 500));
        ped.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                pedWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                pedWindowOpened(evt);
            }
        });
        ped.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl2.setBackground(new java.awt.Color(153, 255, 204));
        tbl2.setForeground(new java.awt.Color(51, 51, 51));
        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artist", "Album", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl2);

        ped.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 460, 186));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Order  Editing...");
        ped.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel2.setText("Quantiy");
        ped.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        tf3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        ped.getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 110, -1));

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        ped.getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 90, 30));

        nxt.setText("Next");
        nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtActionPerformed(evt);
            }
        });
        ped.getContentPane().add(nxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 345, 130, 60));

        rmv.setText("Remove");
        rmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvActionPerformed(evt);
            }
        });
        ped.getContentPane().add(rmv, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 110, 60));
        ped.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        l1.setText("Artist");

        l2.setText("Album");

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });

        cb1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "50", "100", "200", "400", " ", " " }));
        cb1.setAutoscrolls(true);
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "600", "400", "200", "100", "50" }));
        cb2.setAutoscrolls(true);
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        l3.setText("Price range");

        l4.setText("To");

        bs3.setText("Reset");
        bs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bs3ActionPerformed(evt);
            }
        });

        bs1.setText("Search");
        bs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bs1ActionPerformed(evt);
            }
        });

        tbl1.setForeground(new java.awt.Color(51, 51, 51));
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artist", "Album", "Price"
            }
        ));
        jScrollPane1.setViewportView(tbl1);

        bs2.setText("Add");
        bs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bs2ActionPerformed(evt);
            }
        });

        bs4.setText("Next");
        bs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bs4ActionPerformed(evt);
            }
        });

        search.setLayer(l1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(l2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(tf1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(tf2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(cb1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(cb2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(l3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(l4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(bs3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(bs1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(bs2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search.setLayer(bs4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addComponent(l3)
                        .addGap(26, 26, 26)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(l4)
                        .addGap(39, 39, 39)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bs1)
                            .addComponent(bs3))))
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(bs2)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bs4)
                        .addContainerGap())))
            .addGroup(searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bs3)))
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(bs2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bs1)))
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l3)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l4)))
                    .addGroup(searchLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bs4)))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lb1.setBackground(new java.awt.Color(255, 255, 255));
        lb1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        lb1.setText("Artist");

        lb2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        lb2.setText("Album");

        lb3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        lb3.setText("Price");

        Tinsert.setBackground(new java.awt.Color(153, 255, 255));
        Tinsert.setForeground(new java.awt.Color(51, 51, 51));
        Tinsert.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artist", "Album", "Price"
            }
        ));
        jScrollPane4.setViewportView(Tinsert);

        df1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        df1.setForeground(new java.awt.Color(102, 102, 102));
        df1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                df1ActionPerformed(evt);
            }
        });

        df2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        df2.setForeground(new java.awt.Color(102, 102, 102));
        df2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                df2ActionPerformed(evt);
            }
        });

        df3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        df3.setForeground(new java.awt.Color(102, 102, 102));
        df3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                df3ActionPerformed(evt);
            }
        });

        jButton11.setText("Add");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton4.setText("Done");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        nwstk.setLayer(lb1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nwstk.setLayer(lb2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nwstk.setLayer(lb3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nwstk.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nwstk.setLayer(df1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nwstk.setLayer(df2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nwstk.setLayer(df3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nwstk.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nwstk.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout nwstkLayout = new javax.swing.GroupLayout(nwstk);
        nwstk.setLayout(nwstkLayout);
        nwstkLayout.setHorizontalGroup(
            nwstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nwstkLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jButton4)
                .addContainerGap(313, Short.MAX_VALUE))
            .addGroup(nwstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(nwstkLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(nwstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nwstkLayout.createSequentialGroup()
                            .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(df1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(nwstkLayout.createSequentialGroup()
                            .addComponent(lb2)
                            .addGap(49, 49, 49)
                            .addComponent(df2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(nwstkLayout.createSequentialGroup()
                            .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(df3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(nwstkLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(nwstkLayout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        nwstkLayout.setVerticalGroup(
            nwstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nwstkLayout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
            .addGroup(nwstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(nwstkLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(nwstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nwstkLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(df1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(nwstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nwstkLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(df2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(nwstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nwstkLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(df3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(jButton11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        b1.setText("Search");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("ADD");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nwstk, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(26, Short.MAX_VALUE)
                    .addComponent(nwstk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(330, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        bs1ActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
search.setVisible(true);  
nwstk.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
search.setVisible(false);
nwstk.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed

    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed

    }//GEN-LAST:event_cb2ActionPerformed

    private void bs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bs3ActionPerformed
DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
tf1.setText("");
tf2.setText("");
cb1.setSelectedIndex(0);
cb2.setSelectedIndex(0);
model.setRowCount(0);
    }//GEN-LAST:event_bs3ActionPerformed

    private void bs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bs1ActionPerformed
search();        // TODO add your handling code here:
    }//GEN-LAST:event_bs1ActionPerformed

    private void bs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bs2ActionPerformed
try{
    Class.forName("java.sql.DriverManager");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/album","root","aman");
    Statement stmt = con.createStatement();
        String Q="";
       int[] Row = tbl1.getSelectedRows();
      
    int i=0;
    while(i<tbl1.getSelectedRowCount()){
        Q="update songs set selected =true where album"
                + " ='"+tbl1.getValueAt(Row[i], 1) +"';";
        stmt.executeUpdate(Q);
        i++;
    }
}catch(Exception e){
    e.printStackTrace();
}
//selecting
}                                        

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
ped.setVisible(true);
this.dispose();
    }//GEN-LAST:event_bs2ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl2.getModel();
        welRows = tbl2.getSelectedRows();
        int rows = tbl2.getSelectedRowCount();
        rows--;
        int q=Integer.parseInt(tf3.getText());
        while(rows>=0){

            model.setValueAt(q,welRows[rows], 3);
            tf3.setText(null);
            rows--;
        }
    }//GEN-LAST:event_tf3ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        new Page_2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtActionPerformed
        try{DefaultTableModel model1 = (DefaultTableModel) tbl2.getModel();
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/album","root","aman");
            Statement stmt = con.createStatement();
            ResultSet rs;
            String Q="";
            int i=0;
            while(i<tbl2.getRowCount()){
                Q="update songs set Qty ="+tbl2.getValueAt(i, 3) +" where Album='"+tbl2.getValueAt(i, 1)+"';";
                stmt.executeUpdate(Q);
                i++;
            }

            ped.setVisible(false);
        //    d2.setVisible(true);
            this.dispose();
         //   new Music_Store_5().setVisible(false);
        }catch(Exception e){

        }
    }//GEN-LAST:event_nxtActionPerformed

    private void rmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvActionPerformed
        try{
            DefaultTableModel model1 = (DefaultTableModel) tbl2.getModel();
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/album","root","aman");
            Statement stmt = con.createStatement();
            ResultSet rs;
            String Q="";

            int[] rows = tbl2.getSelectedRows();
            for(int i=0;i<rows.length;i++){
                Q="update songs set selected =false where album ='"+tbl2.getValueAt(rows[i]-i, 1) +"';";
                stmt.executeUpdate(Q);
                model1.removeRow(rows[i]-i);
            }

        }catch(Exception e){
            e.printStackTrace();
        }
        //delete from table
        // TODO add your handling code here:
    }//GEN-LAST:event_rmvActionPerformed

    private void pedWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_pedWindowClosing
        System.exit(0);
    }//GEN-LAST:event_pedWindowClosing

    private void pedWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_pedWindowOpened
        try{
            DefaultTableModel model1 = (DefaultTableModel) tbl2.getModel();
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/album","root","aman");
            Statement stmt = con.createStatement();
            ResultSet rs;
            String Q="select * from songs where selected = true;";
            rs = stmt.executeQuery(Q);
            while (rs.next()) {
                model1.addRow(new Object[]{rs.getString("Artist"),rs.getString("Album"),rs.getInt("Price"),1});
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        //to show data in tbl2
    }//GEN-LAST:event_pedWindowOpened

    private void bs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bs4ActionPerformed
       ped.setVisible(true);
        this.dispose();            
// TODO add your handling code here:
    }//GEN-LAST:event_bs4ActionPerformed

    private void df1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_df1ActionPerformed
        search();        // TODO add your handling code here:
    }//GEN-LAST:event_df1ActionPerformed

    private void df2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_df2ActionPerformed
        search();        // TODO add your handling code here:
    }//GEN-LAST:event_df2ActionPerformed

    private void df3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_df3ActionPerformed
        search();        // TODO add your handling code here:
    }//GEN-LAST:event_df3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int p=Integer.parseInt(df3.getText());
        String ar=df1.getText();
        String al=df2.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/album","root","aman");
            Statement stmt = con.createStatement();
            String q="Insert into songs values('"+ar+"','"+al+"',"+p+");";
            stmt.executeUpdate(q);
            JOptionPane.showMessageDialog(this,"Successfully Added");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Page_2().setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
nwstk.setVisible(true);
search.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
 bs1ActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tinsert;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton back;
    private javax.swing.JButton bs1;
    private javax.swing.JButton bs2;
    private javax.swing.JButton bs3;
    private javax.swing.JButton bs4;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JTextField df1;
    private javax.swing.JTextField df2;
    private javax.swing.JTextField df3;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLayeredPane nwstk;
    private javax.swing.JButton nxt;
    private javax.swing.JDialog ped;
    private javax.swing.JButton rmv;
    private javax.swing.JLayeredPane search;
    public javax.swing.JTable tbl1;
    public javax.swing.JTable tbl2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
public void search(){
      DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
    model.setRowCount(0);
  String m=tf1.getText();
  String n=tf2.getText(); 
  String ll=(String) cb1.getSelectedItem();
  String ul=(String) cb2.getSelectedItem();
  
  try{
    Class.forName("java.sql.DriverManager");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/album","root","aman");
    Statement stmt = con.createStatement();
    String q="";
if(tf1.getText().length()>0 && tf2.getText().length()>0){
    q="select * from songs where artist like '"+m+"%'&& album like '"+n+"%'&& price>="+ll+"&&price<"+ul+";";
}else if(tf1.getText().length()>0){
    
    q="select * from songs where artist like '"+m+"%'&& price>="+ll+"&&price<"+ul+";";
}else if(tf2.getText().length()>0){
    q="select * from songs where album like '"+n+"%'&& price>="+ll+"&&price<"+ul+";";
 
}
else{
q="select * from songs where price>="+ll+"&&price<"+ul+";";
}
    ResultSet rs =stmt.executeQuery(q);
    while(rs.next()){
    String art = rs.getString("Artist");
    String al = rs.getString("Album");
    int price=rs.getInt("Price"); 
    model.addRow(new Object[] {art,al,price});
                    }
}
catch(Exception e){
    JOptionPane.showMessageDialog(this, e);
}

}
}
