
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aman Goyal
 */
public class Page_1 extends javax.swing.JFrame {
 String username;
 String password;
 String name;
 int checkadmin;
    /**
     * Creates new form Page_1
     */
    public Page_1() {    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.JFrame();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        music_search = new javax.swing.JButton();
        emp_search = new javax.swing.JButton();
        cust_detail = new javax.swing.JButton();
        deal_detail = new javax.swing.JButton();
        import_detail = new javax.swing.JButton();
        cust_record = new javax.swing.JButton();
        album_record = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        msearch = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        l1 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        bs3 = new javax.swing.JButton();
        bs1 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        l4 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        l5 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        esearch = new javax.swing.JFrame();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf9 = new javax.swing.JTextField();
        tf10 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        bs4 = new javax.swing.JButton();
        emp = new javax.swing.JFrame();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        tf2 = new javax.swing.JPasswordField();
        exit = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();

        admin.setMinimumSize(new java.awt.Dimension(1000, 1000));
        admin.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                adminWindowActivated(evt);
            }
        });

        lb3.setText("Username -->");

        music_search.setText("Music Search");
        music_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                music_searchActionPerformed(evt);
            }
        });

        emp_search.setText("Employee Search");
        emp_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_searchActionPerformed(evt);
            }
        });

        cust_detail.setText("Customer Details");

        deal_detail.setText("Dealer Details");
        deal_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deal_detailActionPerformed(evt);
            }
        });

        import_detail.setText("Import Details");
        import_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                import_detailActionPerformed(evt);
            }
        });

        cust_record.setText("Customer Records");

        album_record.setText("Album Records");

        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin.getContentPane());
        admin.getContentPane().setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminLayout.createSequentialGroup()
                        .addComponent(cust_detail)
                        .addGap(40, 40, 40)
                        .addComponent(album_record)))
                .addGap(22, 22, 22)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(deal_detail))
                    .addComponent(import_detail))
                .addGap(18, 18, 18)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addComponent(music_search)
                        .addGap(28, 28, 28)
                        .addComponent(cust_record))
                    .addGroup(adminLayout.createSequentialGroup()
                        .addComponent(emp_search)
                        .addGap(42, 42, 42)
                        .addComponent(jButton4)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cust_record)
                        .addComponent(import_detail)
                        .addComponent(music_search))
                    .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cust_detail)
                    .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(album_record)
                        .addComponent(deal_detail)
                        .addComponent(emp_search)
                        .addComponent(jButton4)))
                .addContainerGap(531, Short.MAX_VALUE))
        );

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Album", "Artist", "Price", "Type", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl1);

        l1.setText("Artist");

        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });

        l2.setText("Album");

        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });

        bs3.setText("Reset");
        bs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bs3ActionPerformed(evt);
            }
        });

        bs1.setText("Search");
        bs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bs1ActionPerformed(evt);
            }
        });

        l3.setText("Price range");

        cb1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "50", "100", "200", "400", " ", " " }));
        cb1.setAutoscrolls(true);
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        l4.setText("To");

        cb2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "600", "400", "200", "100", "50" }));
        cb2.setAutoscrolls(true);
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        l5.setText("Type");

        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });

        l6.setText("Year");

        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout msearchLayout = new javax.swing.GroupLayout(msearch.getContentPane());
        msearch.getContentPane().setLayout(msearchLayout);
        msearchLayout.setHorizontalGroup(
            msearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msearchLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(msearchLayout.createSequentialGroup()
                .addGroup(msearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(msearchLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(msearchLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(l3)
                        .addGap(26, 26, 26)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(l4)
                        .addGap(39, 39, 39)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(bs1)
                        .addGap(18, 18, 18)
                        .addComponent(bs3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(msearchLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        msearchLayout.setVerticalGroup(
            msearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msearchLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(msearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(msearchLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(msearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(msearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(msearchLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(msearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addGroup(msearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(msearchLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(l3))
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(msearchLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(l4))
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(msearchLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(bs1))
                    .addGroup(msearchLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(msearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bs3)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        l7.setText("Employee ID");

        l8.setText("Name");

        l9.setText("Contact");

        l10.setText("Address");

        jLabel1.setText("E-mail");

        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });

        tf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf8ActionPerformed(evt);
            }
        });

        tf9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf9ActionPerformed(evt);
            }
        });

        tf10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf10ActionPerformed(evt);
            }
        });

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane2.setViewportView(ta1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EmpID", "Name", "Password", "Address", "Email address", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl2);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bs4.setText("Reset");
        bs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bs4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout esearchLayout = new javax.swing.GroupLayout(esearch.getContentPane());
        esearch.getContentPane().setLayout(esearchLayout);
        esearchLayout.setHorizontalGroup(
            esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(esearchLayout.createSequentialGroup()
                        .addGroup(esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(esearchLayout.createSequentialGroup()
                                .addComponent(l7)
                                .addGap(33, 33, 33)
                                .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel1))
                            .addGroup(esearchLayout.createSequentialGroup()
                                .addComponent(l10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l8)))
                        .addGroup(esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(esearchLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(esearchLayout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(38, 38, 38)
                                        .addComponent(bs4)
                                        .addGap(42, 42, 42)
                                        .addComponent(jButton3))
                                    .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(esearchLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(esearchLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        esearchLayout.setVerticalGroup(
            esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esearchLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l7)
                    .addComponent(jLabel1)
                    .addComponent(l9)
                    .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(esearchLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(l10))
                    .addGroup(esearchLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(esearchLayout.createSequentialGroup()
                                .addGroup(esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l8)
                                    .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(esearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(bs4)
                                    .addComponent(jButton3))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout empLayout = new javax.swing.GroupLayout(emp.getContentPane());
        emp.getContentPane().setLayout(empLayout);
        empLayout.setHorizontalGroup(
            empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        empLayout.setVerticalGroup(
            empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VASSAV");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lb1.setText("Username");

        lb2.setText("Passcode");

        tf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf1MouseClicked(evt);
            }
        });
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        tf2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf2MouseClicked(evt);
            }
        });
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(tf2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(exit)
                        .addGap(74, 74, 74)))
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb2)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(login))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
username=tf1.getText();
password=new String(tf2.getPassword());
try {
    Class.forName("java.sql.DriverManager");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/musicstore","root","aman");
    Statement stmt = con.createStatement();
    String q="select * from employee where empid='"+username+"'&& password='"+password+"';";
    ResultSet rs ;
    rs=stmt.executeQuery(q);
    if(rs.next()){
        while(rs.next()){
        name = rs.getString("name");  
        checkadmin=rs.getInt("admin");
        }
                  }
    else{
     JOptionPane.showMessageDialog(this,"Invalid Username or Password"); 
        System.exit(0);
       
        }
    }

catch(Exception e){
    JOptionPane.showMessageDialog(this, e);
                    }
JOptionPane.showMessageDialog(this,name);
if(checkadmin==1){
    admin.setVisible(true); 
                   }
else{
    emp.setVisible(true);
    }
this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        loginActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    tf1.setText("Enter Username");
    tf2.setText("");     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void tf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf1MouseClicked
    username=tf1.getText();
        if(username.equals("Enter Username")){
        tf1.setText("");
    } // TODO add your handling code here:
    }//GEN-LAST:event_tf1MouseClicked

    private void tf2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf2MouseClicked
    password=tf2.getText();
        if(password.equals("Enter Password")){
    tf2.setText(""); 
}       // TODO add your handling code here:
    }//GEN-LAST:event_tf2MouseClicked

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
  username=tf1.getText();
        if(username.equals("Enter Username")){
        tf1.setText("");
    }         // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void adminWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_adminWindowActivated
lb4.setText(name);
msearch.setVisible(false);
esearch.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_adminWindowActivated

    private void emp_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_searchActionPerformed
        esearch.setVisible(true);        // TODO add your handling code here:
        
    }//GEN-LAST:event_emp_searchActionPerformed

    private void music_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_music_searchActionPerformed
msearch.setVisible(true);
admin.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_music_searchActionPerformed

    private void import_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_import_detailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_import_detailActionPerformed

    private void tf10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf10ActionPerformed

    private void tf9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf9ActionPerformed

    private void tf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf8ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
        bs1ActionPerformed(evt);    // TODO add your handling code here:
    }//GEN-LAST:event_tf6ActionPerformed

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        bs1ActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tf5ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed

    }//GEN-LAST:event_cb2ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed

    }//GEN-LAST:event_cb1ActionPerformed

    private void bs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bs1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        model.setRowCount(0);
        String artist=tf3.getText();
        String album=tf4.getText();
        String type=tf5.getText();
        String year=tf6.getText();
        String ll=(String) cb1.getSelectedItem();
        String ul=(String) cb2.getSelectedItem();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/musicstore","root","aman");
            Statement stmt = con.createStatement();
            String q="";
            if(tf3.getText().length()>0 && tf4.getText().length()>0 && tf5.getText().length()>0 && tf6.getText().length()>0){
                q="select * from songs where artist like '"+artist+"%'&& album like '"+album+"%'&& price>="+ll+"&& price<"+ul+"&& type like '"+type+"%'&& year ="+year+";";
            }
            else if(tf3.getText().length()>0){
                q="select * from songs where artist like '"+artist+"%'&& price>="+ll+"&& price<"+ul+";";
            }
            else if(tf4.getText().length()>0){
                q="select * from songs where album like '%"+album+"%'&& price>="+ll+"&&price<"+ul+";";
            }
            else if(tf5.getText().length()>0){
                q="select * from songs where type like '%"+type+"%'&& price>="+ll+"&&price<"+ul+";";
            }
            else if(tf6.getText().length()>0){
                q="select * from songs where year ="+year+"&& price>="+ll+"&&price<"+ul+";";
            }
            else if(tf3.getText().length()>0 && tf4.getText().length()>0){
                q="select * from songs where artist like '%"+artist+"%'&& album like '%"+album+"%'&& price>="+ll+"&&price<"+ul+";";
            }
            else if(tf3.getText().length()>0  && tf5.getText().length()>0 ){
                q="select * from songs where artist like '%"+artist+"%'&& price>="+ll+"&&price<"+ul+"&& type like '%"+type+"%';";
            }
            else if(tf3.getText().length()>0 && tf6.getText().length()>0){
                q="select * from songs where artist like '%"+artist+"%'&& price>="+ll+"&&price<"+ul+"&& year ="+year+";";
            }
            else if(tf4.getText().length()>0 && tf5.getText().length()>0 ){
                q="select * from songs where album like '%"+album+"%'&& price>="+ll+"&&price<"+ul+"&& type like '%"+type+"%';";
            }
            else if(tf4.getText().length()>0 && tf6.getText().length()>0){
                q="select * from songs where album like '%"+album+"%'&& price>="+ll+"&&price<"+ul+" && year ="+year+";";
            }
            else if(tf5.getText().length()>0 && tf6.getText().length()>0){
                q="select * from songs where price>="+ll+"&&price<"+ul+"&& type like '%"+type+"%'&& year ="+year+";";
            }
            else if(tf3.getText().length()>0 && tf4.getText().length()>0 && tf5.getText().length()>0){
                q="select * from songs where artist like '%"+artist+"%'&& album like '%"+album+"%'&& price>="+ll+"&&price<"+ul+"&& type like '%"+type+"%';";
            }
            else if(tf3.getText().length()>0 && tf4.getText().length()>0 && tf6.getText().length()>0){
                q="select * from songs where artist like '%"+artist+"%'&& album like '%"+album+"%'&& price>="+ll+"&&price<"+ul+" && year ="+year+";";
            }
            else if(tf3.getText().length()>0 && tf5.getText().length()>0 && tf6.getText().length()>0){
                q="select * from songs where artist like '%"+artist+"%'&& price>="+ll+"&&price<"+ul+"&& type like '%"+type+"%'&& year ="+year+";";
            }
            else if(tf4.getText().length()>0 && tf5.getText().length()>0 && tf6.getText().length()>0){
                q="select * from songs where album like '%"+album+"%'&& price>="+ll+"&&price<"+ul+"&& type like '%"+type+"%'&& year ="+year+";";
            }
            else{
                q="select * from songs where price>="+ll+"&&price<"+ul+";";
            }
            ResultSet rs =stmt.executeQuery(q);
            while(rs.next()){
                //JOptionPane.showMessageDialog(this,rs);
                String art = rs.getString("artist");
                String al = rs.getString("album");
                int price=rs.getInt("price");
                String typ=rs.getString("type");
                int yr=rs.getInt("year");
                model.addRow(new Object[] {al,art,price,typ,yr});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bs1ActionPerformed

    private void bs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bs3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        tf5.setText("");
        tf6.setText("");
        tf3.setText("");
        tf4.setText("");
        cb1.setSelectedIndex(0);
        cb2.setSelectedIndex(0);
        model.setRowCount(0);
    }//GEN-LAST:event_bs3ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        bs1ActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        bs1ActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void deal_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deal_detailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deal_detailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        admin.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        admin.setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bs4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl2.getModel();
        tf7.setText("");
        tf8.setText("");
        tf9.setText("");
        tf10.setText("");
        ta1.setText("");
        model.setRowCount(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_bs4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame admin;
    private javax.swing.JButton album_record;
    private javax.swing.JButton bs1;
    private javax.swing.JButton bs3;
    private javax.swing.JButton bs4;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton cust_detail;
    private javax.swing.JButton cust_record;
    private javax.swing.JButton deal_detail;
    private javax.swing.JFrame emp;
    private javax.swing.JButton emp_search;
    private javax.swing.JFrame esearch;
    private javax.swing.JButton exit;
    private javax.swing.JButton import_detail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JButton login;
    private javax.swing.JFrame msearch;
    private javax.swing.JButton music_search;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JPasswordField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration//GEN-END:variables
}
